# Generated by Django 4.2.7 on 2023-11-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('question_count', models.PositiveSmallIntegerField()),
                ('right_answers', models.PositiveSmallIntegerField()),
                ('wrong_answers', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
