# Generated by Django 4.2.7 on 2023-11-28 13:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='question_count',
            new_name='number_of_questions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='right_answers',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='wrong_answers',
        ),
        migrations.AddField(
            model_name='quiz',
            name='date_of_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('choice_A', models.CharField(max_length=100)),
                ('choice_B', models.CharField(max_length=100)),
                ('choice_C', models.CharField(max_length=100)),
                ('choice_D', models.CharField(max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
            ],
        ),
    ]
