# Generated by Django 4.2.7 on 2023-11-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_question_id_alter_question_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_A',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_B',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_C',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_D',
        ),
        migrations.AddField(
            model_name='question',
            name='user_answer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
