# Generated by Django 4.2.7 on 2023-11-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_remove_question_choice_a_remove_question_choice_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='number_of_questions',
        ),
    ]
