# Generated by Django 4.2.7 on 2023-11-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_remove_quiz_number_of_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='date_of_creation',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_text',
            field=models.TextField(blank=True, default='Default question text', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user_answer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
