# Generated by Django 4.2.7 on 2023-11-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_remove_quiz_date_of_creation_quiz_question_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='user_answer',
        ),
    ]
