# Generated by Django 4.2.7 on 2023-11-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_question_remove_quiz_question_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.TextField(max_length=100),
        ),
    ]
