# Generated by Django 4.2.7 on 2023-11-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_alter_question_id_alter_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user_answer',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
