# Generated by Django 4.2.7 on 2023-11-30 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='status',
            new_name='is_correct',
        ),
    ]
