# Generated by Django 4.2.7 on 2023-11-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_alter_option_id_alter_option_question_and_more'),
    ]

    operations = [
    ]
