# Generated by Django 4.2.7 on 2023-11-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0016_auto_20231130_0829'),
    ]

    operations = [
    ]
