# Generated by Django 4.2.7 on 2023-11-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_auto_20231130_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_a',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_b',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_c',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_d',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
