# Generated by Django 4.2.7 on 2023-11-30 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0022_remove_question_is_correct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_d',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_answer',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.question')),
            ],
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_choice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='quizzes.choice'),
            preserve_default=False,
        ),
    ]
