# Generated by Django 4.2.7 on 2023-12-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0023_remove_question_choice_a_remove_question_choice_b_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Option',
        ),
    ]
